### ISSUE TITLE
Pending virtual disk request shows Loading...

### ISSUE THREAD

**Issue by keerti1** [msasad/baadal#12]
URL : https://10.237.23.53/baadal/admin/security_groups.html#

Steps to reproduce bug:
1. Click Admin  menu then select Disk Requests.
2. Page is showing Loading for long time.
![pending virtual disk request page shows loading only](https://cloud.githubusercontent.com/assets/7147215/14908686/fa0ef190-0df7-11e6-9c48-59510d5ee085.png)

**Comment by msasad** [comment]
@keerti1 Missing table was created. Please review.

**Comment by msasad** [comment]
@keerti1 fix has been added. Please review.
