### ISSUE TITLE
My Request page is taking very long time to load

### ISSUE THREAD

**Issue by keerti1** [msasad/baadal#13]
URL : https://10.237.23.53/baadal/user/my_requests_list/

Step : Click on User menu then My Request.
Issue: Page is taking very long time to show.
![my request page is taking very long time to load](https://cloud.githubusercontent.com/assets/7147215/14908852/41655816-0dfa-11e6-8f81-a647222f1d8d.png)

**Comment by msasad** [comment]
@keerti1 please review.

**Comment by msasad** [comment]
@keerti1 Please review.
