### ISSUE TITLE
VM clone request page is showing loading and Wrong title

### ISSUE THREAD

**Issue by keerti1** [msasad/baadal#14]
URL : https://10.237.23.53/baadal/admin/clone_requests.html

Steps to reproduce bug:
1. Click Admin menu then Vm clone request.
 Issues:
1. Page is showing loading only 
2. It has wrong title "Pending VM Resize Requests
![vm clone request page showing loading andand shows title pending vm resize request](https://cloud.githubusercontent.com/assets/7147215/14909152/b8a0bf3a-0dfd-11e6-972c-1e89df2e911e.png)
"

**Comment by msasad** [comment]
@keerti1 commits added dcd780811e533e3184b9422ab82b9af961ac8ed0 and b3ffe6853223e4bd99a46541242f25436fb43992
please review.
