### ISSUE TITLE
Delete Button for my request not working

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#25]
URL: https://10.237.23.53/baadal/user/my_requests_list/
Steps to reproduce bug:-
1.Login and request a vm from user menu.
2.Click user menu then my requests.
3.Click Delete button under action menu.
Issue:-
The request is not deleted on clicking delete button.
![screenshot from 2016-05-10 11 22 58](https://cloud.githubusercontent.com/assets/8348585/15136874/0bd72948-16a3-11e6-851f-0851860b91e4.png)

**Comment by msasad** [comment]
@suvajitsarkar Please review.

**Comment by suvajitsarkar** [comment]
Its not working for a user with user rights or faculty rights. Its working for user with admin rights only. Same is for edit configuration. It works only for admin user.
![screenshot from 2016-05-12 12 16 47](https://cloud.githubusercontent.com/assets/8348585/15206406/8698f1b2-183c-11e6-9c04-687fd173202e.png)

**Comment by msasad** [comment]
@suvajitsarkar Please review.
