### ISSUE TITLE
Duplicate VM name allowed to be requested

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#26]
URL:- https://10.237.23.53/baadal/user/request/
Steps:
1.Login and click request VM.
2.Fill in the form and click submit.
3.Click submit again.
4.Check pending request page from admin menu.
![screenshot from 2016-05-10 11 35 07](https://cloud.githubusercontent.com/assets/8348585/15137143/57e8815e-16a5-11e6-86e7-59d9be9561a8.png)

Issue:
Duplicate name VMs should not be allowed to request.
Both the VMs with same name can be approved resulting in a redundant state.
![screenshot from 2016-05-10 11 36 24](https://cloud.githubusercontent.com/assets/8348585/15137165/819a2b24-16a5-11e6-9d75-4536ee10bb22.png)

**Comment by msasad** [comment]
Openstack backend allows VMs of same to be created. Each VM is uniquely identified by its ID.
