### ISSUE TITLE
Assigning Public IP to a VM not working

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#27]
Steps:-
1.Login and request a VM with public IP required as yes.
2. Approve the VM from pending VM under admin menu.
Issues:-
No information showing on Baadal GUI for Public IP
![screenshot from 2016-05-10 12 03 35](https://cloud.githubusercontent.com/assets/8348585/15137561/46a0c214-16a8-11e6-8909-5af8294b0670.png)

Also From the console ifconfig shows no public IP.
![screenshot from 2016-05-10 12 03 24](https://cloud.githubusercontent.com/assets/8348585/15137577/6109e450-16a8-11e6-8d15-2cf1384b37e8.png)

**Comment by msasad** [comment]
@nalinivarshney Please allocate a public IP pool
