### ISSUE TITLE
No option for user to assign public ip to an existing VM.

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#28]
Steps:-
1.Login and click home.
2.Click on settings button of any VM.
Issue:
No option to request for public ip.
![screenshot from 2016-05-10 12 25 51](https://cloud.githubusercontent.com/assets/8348585/15138093/39b9bc42-16ab-11e6-8fae-fd1c49795945.png)

**Comment by paritoshpuri** [comment]
@suvajitsarkar  please review

**Comment by suvajitsarkar** [comment]
It is not working.
After requesting for a public ip, click on pending public ip link from admin menu. The page keeps on loading.
![screenshot from 2016-06-09 15 17 22](https://cloud.githubusercontent.com/assets/8348585/15925690/d3f156c8-2e55-11e6-925d-5301ad78fc76.png)

**Comment by paritoshpuri** [comment]
@suvajitsarkar please review

**Comment by suvajitsarkar** [comment]
![screenshot from 2016-06-09 15 52 50](https://cloud.githubusercontent.com/assets/8348585/15926612/9b8162c4-2e5a-11e6-9075-1e9c5ad430da.png)

**Comment by paritoshpuri** [comment]
@suvajitsarkar: create vm by using security domain demo-net.
