### ISSUE TITLE
VM resize button not working

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#29]
Steps:-
1. Login and click on settings button of a VM from user menu.
2. Click Request Resize button then submit.
Issue:-
Nothing is displayed on GUI.Also Pending VM Resize Requests page under admin menu shows no resize request.
![screenshot from 2016-05-10 16 51 16](https://cloud.githubusercontent.com/assets/8348585/15144940/515f5b70-16d0-11e6-99c7-2bd937f6a989.png)

**Comment by msasad** [comment]
@suvajitsarkar Please review.
