### ISSUE TITLE
Error in My request page under user menu

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#30]
Steps:-
1. Request a Vm from one user.
2. Login as a different user
3. Check My request link under user menu.
Issue:-
VM requested by one user is displayed in my request page of another user.
![screenshot from 2016-05-11 12 14 36](https://cloud.githubusercontent.com/assets/8348585/15172424/9ab20b58-1773-11e6-99f5-df19d2b70705.png)

**Comment by msasad** [comment]
@suvajitsarkar Please review.
