### ISSUE TITLE
Request VM with wrong faculty name

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#31]
Step:-
1. Login with user rights only.
2. Request a VM with wrong faculty name.
Issue:-
The request is submitted even faculty name is wrong.
![screenshot from 2016-05-11 12 30 11](https://cloud.githubusercontent.com/assets/8348585/15172746/7638ef06-1775-11e6-8d92-b1860010ef87.png)

**Comment by msasad** [comment]
@suvajitsarkar Please review.
