### ISSUE TITLE
The HTML field entry does not change accordingly.

### ISSUE THREAD

**Issue by paritoshpuri** [msasad/baadal#37]
URL:- https://10.237.23.53/baadal/user/
Steps:
1.Login and click setting button of VM.
2.Click any button the HTML entry changes accordingly.
3. Now click the request virtual disk button.
4. Now click any other button HTML entry remained unchainged
![git_bug](https://cloud.githubusercontent.com/assets/8348555/15531416/ee1ba4de-2277-11e6-8ffb-35af01eed8d2.png)
.

**Comment by msasad** [comment]
@paritoshpuri pls review
