### ISSUE TITLE
VM clone request reject 

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#45]
Steps:
1. Login as an admin user.
2. Click on admin menu, then VM clone requests.
3. Click on reject button of any request.

Issues:
A pop up message should be given to notify the user that the request is rejected.
![screenshot from 2016-06-07 13 36 37](https://cloud.githubusercontent.com/assets/8348585/15850481/cbc036e6-2cb5-11e6-92e5-8361f24086d7.png)

**Comment by msasad** [comment]
@suvajitsarkar Pl review.
