### ISSUE TITLE
Clone request accepted by user makes the user owner of the clone

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#47]
Steps to reproduce the bug:
1. Login and click settings button of a vm.
2. Click on clone request button.
3 Login as another user with admin rights.
4 Approve the clone request from "Pending VM Clone Requests" page.
Issue:
The clone created is owned by the admin who approves the request.
![screenshot from 2016-06-09 15 22 44](https://cloud.githubusercontent.com/assets/8348585/15926017/5984d3c2-2e57-11e6-9cad-63897c0143cf.png)

**Comment by msasad** [comment]
@suvajitsarkar Pl review.
