### ISSUE TITLE
VNC console button not working for regular user

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#49]
![screenshot from 2016-06-13 12 06 06](https://cloud.githubusercontent.com/assets/8348585/15999056/851e8c60-3160-11e6-8300-18b7e610cf51.png)
![screenshot from 2016-06-13 12 06 13](https://cloud.githubusercontent.com/assets/8348585/15999076/b4e0ed44-3160-11e6-8ebc-93b3b08ee3df.png)

**Comment by msasad** [comment]
@suvajitsarkar Pl review.
