### ISSUE TITLE
Edit vm request from admin menu

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#50]
Steps:-
1. Login and request a vm.
2. Login as admin and click 'vm requests' link. 
![screenshot from 2016-06-13 12 10 34](https://cloud.githubusercontent.com/assets/8348585/15999258/03662442-3162-11e6-9235-c747dfbfeed8.png)
3. Click edit button.
![screenshot from 2016-06-13 12 10 39](https://cloud.githubusercontent.com/assets/8348585/15999275/23b11932-3162-11e6-9549-3d56ad19cf9c.png)

ISSUE:-
Different configuration than the one requested is displayed on the page.

**Comment by msasad** [comment]
@suvajitsarkar Please review,
