### ISSUE TITLE
APPROVAL STATUS SHOLUD BE DISPLAYED FOR A PENDING VM REQUEST

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#52]
![screenshot from 2016-06-13 12 50 17](https://cloud.githubusercontent.com/assets/8348585/16000072/7d53e276-3167-11e6-92b5-59f669bcd462.png)

![screenshot from 2016-06-13 13 01 09](https://cloud.githubusercontent.com/assets/8348585/16000112/d289aafa-3167-11e6-89d0-4653ee076d7c.png)

**Comment by paritoshpuri** [comment]
@suvajitsarkar please review
