### ISSUE TITLE
Manage user button not working

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#53]
![screenshot from 2016-06-13 13 22 56](https://cloud.githubusercontent.com/assets/8348585/16000471/3ea82444-316a-11e6-904c-2e240912f8ab.png)

On clicking the button users attached to the VM should be displayed. Also the owner of the vm should be able to add more or remove existing users from the VM.

**Comment by msasad** [comment]
@suvajitsarkar Please review.

**Comment by suvajitsarkar** [comment]
Its not working....
![screenshot from 2016-06-20 17 18 27](https://cloud.githubusercontent.com/assets/8348585/16193186/4b5cd300-370b-11e6-8742-ce48238ed2a5.png)

**Comment by msasad** [comment]
Nova policy was updated to allow compute:update_instance_metadata .
Please review.

**Comment by msasad** [comment]
@suvajitsarkar Please review.
