### ISSUE TITLE
Account Request error

### ISSUE THREAD

**Issue by suvajitsarkar** [msasad/baadal#64]
Steps to reproduce the bug:
1.Request an account for a user
2.Reject the request from admin menu
3.Request an account with the same data as before.
4.Try to accept the request from account request tab.
Bug:
It gives an error as account cannot be created as in the snapshot below
![screenshot from 2016-09-09 14 30 33](https://cloud.githubusercontent.com/assets/8348585/18381711/34925760-769b-11e6-8150-0867d909d38b.png)

**Comment by paritoshpuri** [comment]
please review
