### ISSUE TITLE
No Error Notification in new vm request page

### ISSUE THREAD

**Issue by keerti1** [msasad/baadal#8]
URL : https://10.237.23.53/request

Steps to reproduce bug:
Enter a invalid name like "_sfjhjf-". It will not show any errror message only field is marked red.

There should be error message of invalid value and valid values possible for this field.
![wrong vm name dont pop up error message](https://cloud.githubusercontent.com/assets/7147215/14841895/ec2f9db6-0c5f-11e6-99ad-8bcaa431ff1e.png)

**Comment by msasad** [comment]
Fixed by commit 1ad7e2b8bb71eaea4aca6ea15fe9907166a7af51

**Comment by keerti1** [comment]
It is not accepting _ in starting... You can write name should not start with _ or -.

Other then this there is no pop up window on entering wrong value for vm_name. Ther shoud be some popup window or message.

**Comment by msasad** [comment]
Yes, _ or - are not allowed in the starting or the end.

Is a popup really necessary? The point is that, the user should get to know why the input validation has failed. And the instructions on the right make it clear. Is it necessary that the information be conveyed by popup only and not by any other means?

**Comment by suvajitsarkar** [comment]
Attachment of old baadal deployment for entering wrong entry for vm name.
![screenshot from 2016-04-29 12 35 33](https://cloud.githubusercontent.com/assets/8348585/14909991/2a1f0370-0e07-11e6-872e-085d2394f536.png)

**Comment by msasad** [comment]
@keerti1 please review.
