### ISSUE TITLE
Modify pending request window remains there even after submission 

### ISSUE THREAD

**Issue by keerti1** [msasad/baadal#9]
URL: https://10.237.23.53/baadal/admin/pending_requests_list.html

Steps to reproduce bug:
1. Go to "Pending Vm Request" page.
2. Click on edit button, it will pop up modify "pending request window".
3. Make whatever changes you want and click "Modify and Approve" button.

Issues to be solved:
1. "pending request window" Window is not going. 
2. No notification message pops up stating request is submitted or not.
3. Even those 3 buttons present in Action field should also be replaced with a button representing work in progress. so that no one will be able 
![window remain even after button click](https://cloud.githubusercontent.com/assets/7147215/14842277/4b49514a-0c63-11e6-95fa-84b5a96123ff.png)
change configuration of vm which is already in process of creation.

**Comment by msasad** [comment]
@suvajitsarkar @paritoshpuri Please file new bugs at github. Also refer to this bug as sample for how bugs should be filed.

**Comment by keerti1** [comment]
Same issue is coming in My Request.

Steps:
Go to users then My Requests
1. Click on delete button  (Button not workin)

Other bug steps:
1. Click on Edit Button
2. modify whatever you want
3. Click  Modify an Approve button

![my request modify pending request is not going](https://cloud.githubusercontent.com/assets/7147215/14908934/414385e6-0dfb-11e6-8853-ffa86a7688a0.png)
issues:
1. Delete button not working
2. Modify pending request is not going after Modify an Approve button click.

**Comment by msasad** [comment]
@keerti1 Please review.
